# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Posy-Plugin-Flickr-Photo
version:      0.2
version_from: lib/Posy/Plugin/Flickr/Photo.pm
installdirs:  site
requires:
    Flickr::API:                   0
    Posy:                          0.97
    Posy::Core:                    0.97
    Posy::Plugin::Cache::File:     0.1
    Test::More:                    0
    XML::XPath:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
